### ISSUE TITLE
Color and feature tracking image alignment on Phab2Pro

### ISSUE THREAD

**Issue by smits** [Intermodalics/tango_ros#135] opened 2017-01-26 12:01 UTC
The color and feature tracking images are not aligned with the depth camera.  When holding the phab2pro the point cloud seems to be correctly aligned the feature tracking and color camera seem to be rotated either 90 degrees to the left or right, I think from a user perspective we need to provide an option to correctly align the images.

**Comment by PerrineAguiar** [comment] 2017-10-02 15:29
Duplicate of #296.

**Closed by PerrineAguiar** 2017-10-02 15:29 UTC
